const RAW_MATCHES = [
  {
    "id": 1,
    "stage": "group",
    "group": "A",
    "date": "2026-06-11",
    "time": "13:00",
    "venue": "Mexico City",
    "home": "mexico",
    "away": "south-africa"
  },
  {
    "id": 2,
    "stage": "group",
    "group": "A",
    "date": "2026-06-11",
    "time": "20:00",
    "venue": "Guadalajara",
    "home": "korea-republic",
    "away": "czechia"
  },
  {
    "id": 3,
    "stage": "group",
    "group": "B",
    "date": "2026-06-12",
    "time": "15:00",
    "venue": "Toronto",
    "home": "canada",
    "away": "bosnia-herzegovina"
  },
  {
    "id": 4,
    "stage": "group",
    "group": "D",
    "date": "2026-06-12",
    "time": "18:00",
    "venue": "Los Angeles",
    "home": "usa",
    "away": "paraguay"
  },
  {
    "id": 5,
    "stage": "group",
    "group": "C",
    "date": "2026-06-13",
    "time": "21:00",
    "venue": "Boston",
    "home": "haiti",
    "away": "scotland"
  },
  {
    "id": 6,
    "stage": "group",
    "group": "D",
    "date": "2026-06-13",
    "time": "21:00",
    "venue": "Vancouver",
    "home": "australia",
    "away": "turkiye"
  },
  {
    "id": 7,
    "stage": "group",
    "group": "C",
    "date": "2026-06-13",
    "time": "18:00",
    "venue": "New York/New Jersey",
    "home": "brazil",
    "away": "morocco"
  },
  {
    "id": 8,
    "stage": "group",
    "group": "B",
    "date": "2026-06-13",
    "time": "12:00",
    "venue": "San Francisco Bay Area",
    "home": "qatar",
    "away": "switzerland"
  },
  {
    "id": 9,
    "stage": "group",
    "group": "E",
    "date": "2026-06-14",
    "time": "19:00",
    "venue": "Philadelphia",
    "home": "ivory-coast",
    "away": "ecuador"
  },
  {
    "id": 10,
    "stage": "group",
    "group": "E",
    "date": "2026-06-14",
    "time": "12:00",
    "venue": "Houston",
    "home": "germany",
    "away": "curacao"
  },
  {
    "id": 11,
    "stage": "group",
    "group": "F",
    "date": "2026-06-14",
    "time": "15:00",
    "venue": "Dallas",
    "home": "netherlands",
    "away": "japan"
  },
  {
    "id": 12,
    "stage": "group",
    "group": "F",
    "date": "2026-06-14",
    "time": "20:00",
    "venue": "Monterrey",
    "home": "sweden",
    "away": "tunisia"
  },
  {
    "id": 13,
    "stage": "group",
    "group": "H",
    "date": "2026-06-15",
    "time": "18:00",
    "venue": "Miami",
    "home": "saudi-arabia",
    "away": "uruguay"
  },
  {
    "id": 14,
    "stage": "group",
    "group": "H",
    "date": "2026-06-15",
    "time": "12:00",
    "venue": "Atlanta",
    "home": "spain",
    "away": "cape-verde"
  },
  {
    "id": 15,
    "stage": "group",
    "group": "G",
    "date": "2026-06-15",
    "time": "18:00",
    "venue": "Los Angeles",
    "home": "iran",
    "away": "new-zealand"
  },
  {
    "id": 16,
    "stage": "group",
    "group": "G",
    "date": "2026-06-15",
    "time": "12:00",
    "venue": "Seattle",
    "home": "belgium",
    "away": "egypt"
  },
  {
    "id": 17,
    "stage": "group",
    "group": "I",
    "date": "2026-06-16",
    "time": "15:00",
    "venue": "New York/New Jersey",
    "home": "france",
    "away": "senegal"
  },
  {
    "id": 18,
    "stage": "group",
    "group": "I",
    "date": "2026-06-16",
    "time": "18:00",
    "venue": "Boston",
    "home": "iraq",
    "away": "norway"
  },
  {
    "id": 19,
    "stage": "group",
    "group": "J",
    "date": "2026-06-16",
    "time": "20:00",
    "venue": "Kansas City",
    "home": "argentina",
    "away": "algeria"
  },
  {
    "id": 20,
    "stage": "group",
    "group": "J",
    "date": "2026-06-16",
    "time": "21:00",
    "venue": "San Francisco Bay Area",
    "home": "austria",
    "away": "jordan"
  },
  {
    "id": 21,
    "stage": "group",
    "group": "L",
    "date": "2026-06-17",
    "time": "19:00",
    "venue": "Toronto",
    "home": "ghana",
    "away": "panama"
  },
  {
    "id": 22,
    "stage": "group",
    "group": "L",
    "date": "2026-06-17",
    "time": "15:00",
    "venue": "Dallas",
    "home": "england",
    "away": "croatia"
  },
  {
    "id": 23,
    "stage": "group",
    "group": "K",
    "date": "2026-06-17",
    "time": "12:00",
    "venue": "Houston",
    "home": "portugal",
    "away": "congo-dr"
  },
  {
    "id": 24,
    "stage": "group",
    "group": "K",
    "date": "2026-06-17",
    "time": "20:00",
    "venue": "Mexico City",
    "home": "uzbekistan",
    "away": "colombia"
  },
  {
    "id": 25,
    "stage": "group",
    "group": "A",
    "date": "2026-06-18",
    "time": "12:00",
    "venue": "Atlanta",
    "home": "czechia",
    "away": "south-africa"
  },
  {
    "id": 26,
    "stage": "group",
    "group": "B",
    "date": "2026-06-18",
    "time": "12:00",
    "venue": "Los Angeles",
    "home": "switzerland",
    "away": "bosnia-herzegovina"
  },
  {
    "id": 27,
    "stage": "group",
    "group": "B",
    "date": "2026-06-18",
    "time": "15:00",
    "venue": "Vancouver",
    "home": "canada",
    "away": "qatar"
  },
  {
    "id": 28,
    "stage": "group",
    "group": "A",
    "date": "2026-06-18",
    "time": "19:00",
    "venue": "Guadalajara",
    "home": "mexico",
    "away": "korea-republic"
  },
  {
    "id": 29,
    "stage": "group",
    "group": "C",
    "date": "2026-06-19",
    "time": "21:00",
    "venue": "Philadelphia",
    "home": "brazil",
    "away": "haiti"
  },
  {
    "id": 30,
    "stage": "group",
    "group": "C",
    "date": "2026-06-19",
    "time": "18:00",
    "venue": "Boston",
    "home": "scotland",
    "away": "morocco"
  },
  {
    "id": 31,
    "stage": "group",
    "group": "D",
    "date": "2026-06-19",
    "time": "20:00",
    "venue": "San Francisco Bay Area",
    "home": "turkiye",
    "away": "paraguay"
  },
  {
    "id": 32,
    "stage": "group",
    "group": "D",
    "date": "2026-06-19",
    "time": "12:00",
    "venue": "Seattle",
    "home": "usa",
    "away": "australia"
  },
  {
    "id": 33,
    "stage": "group",
    "group": "E",
    "date": "2026-06-20",
    "time": "16:00",
    "venue": "Toronto",
    "home": "germany",
    "away": "ivory-coast"
  },
  {
    "id": 34,
    "stage": "group",
    "group": "E",
    "date": "2026-06-20",
    "time": "19:00",
    "venue": "Kansas City",
    "home": "ecuador",
    "away": "curacao"
  },
  {
    "id": 35,
    "stage": "group",
    "group": "F",
    "date": "2026-06-20",
    "time": "12:00",
    "venue": "Houston",
    "home": "netherlands",
    "away": "sweden"
  },
  {
    "id": 36,
    "stage": "group",
    "group": "F",
    "date": "2026-06-20",
    "time": "22:00",
    "venue": "Monterrey",
    "home": "tunisia",
    "away": "japan"
  },
  {
    "id": 37,
    "stage": "group",
    "group": "H",
    "date": "2026-06-21",
    "time": "18:00",
    "venue": "Miami",
    "home": "uruguay",
    "away": "cape-verde"
  },
  {
    "id": 38,
    "stage": "group",
    "group": "H",
    "date": "2026-06-21",
    "time": "12:00",
    "venue": "Atlanta",
    "home": "spain",
    "away": "saudi-arabia"
  },
  {
    "id": 39,
    "stage": "group",
    "group": "G",
    "date": "2026-06-21",
    "time": "12:00",
    "venue": "Los Angeles",
    "home": "belgium",
    "away": "iran"
  },
  {
    "id": 40,
    "stage": "group",
    "group": "G",
    "date": "2026-06-21",
    "time": "18:00",
    "venue": "Vancouver",
    "home": "new-zealand",
    "away": "egypt"
  },
  {
    "id": 41,
    "stage": "group",
    "group": "I",
    "date": "2026-06-22",
    "time": "20:00",
    "venue": "New York/New Jersey",
    "home": "norway",
    "away": "senegal"
  },
  {
    "id": 42,
    "stage": "group",
    "group": "I",
    "date": "2026-06-22",
    "time": "17:00",
    "venue": "Philadelphia",
    "home": "france",
    "away": "iraq"
  },
  {
    "id": 43,
    "stage": "group",
    "group": "J",
    "date": "2026-06-22",
    "time": "12:00",
    "venue": "Dallas",
    "home": "argentina",
    "away": "austria"
  },
  {
    "id": 44,
    "stage": "group",
    "group": "J",
    "date": "2026-06-22",
    "time": "20:00",
    "venue": "San Francisco Bay Area",
    "home": "jordan",
    "away": "algeria"
  },
  {
    "id": 45,
    "stage": "group",
    "group": "L",
    "date": "2026-06-23",
    "time": "16:00",
    "venue": "Boston",
    "home": "england",
    "away": "ghana"
  },
  {
    "id": 46,
    "stage": "group",
    "group": "L",
    "date": "2026-06-23",
    "time": "19:00",
    "venue": "Toronto",
    "home": "panama",
    "away": "croatia"
  },
  {
    "id": 47,
    "stage": "group",
    "group": "K",
    "date": "2026-06-23",
    "time": "12:00",
    "venue": "Houston",
    "home": "portugal",
    "away": "uzbekistan"
  },
  {
    "id": 48,
    "stage": "group",
    "group": "K",
    "date": "2026-06-23",
    "time": "20:00",
    "venue": "Guadalajara",
    "home": "colombia",
    "away": "congo-dr"
  },
  {
    "id": 49,
    "stage": "group",
    "group": "C",
    "date": "2026-06-24",
    "time": "18:00",
    "venue": "Miami",
    "home": "scotland",
    "away": "brazil"
  },
  {
    "id": 50,
    "stage": "group",
    "group": "C",
    "date": "2026-06-24",
    "time": "18:00",
    "venue": "Atlanta",
    "home": "morocco",
    "away": "haiti"
  },
  {
    "id": 51,
    "stage": "group",
    "group": "B",
    "date": "2026-06-24",
    "time": "12:00",
    "venue": "Vancouver",
    "home": "switzerland",
    "away": "canada"
  },
  {
    "id": 52,
    "stage": "group",
    "group": "B",
    "date": "2026-06-24",
    "time": "12:00",
    "venue": "Seattle",
    "home": "bosnia-herzegovina",
    "away": "qatar"
  },
  {
    "id": 53,
    "stage": "group",
    "group": "A",
    "date": "2026-06-24",
    "time": "19:00",
    "venue": "Mexico City",
    "home": "czechia",
    "away": "mexico"
  },
  {
    "id": 54,
    "stage": "group",
    "group": "A",
    "date": "2026-06-24",
    "time": "19:00",
    "venue": "Monterrey",
    "home": "south-africa",
    "away": "korea-republic"
  },
  {
    "id": 55,
    "stage": "group",
    "group": "E",
    "date": "2026-06-25",
    "time": "16:00",
    "venue": "Philadelphia",
    "home": "curacao",
    "away": "ivory-coast"
  },
  {
    "id": 56,
    "stage": "group",
    "group": "E",
    "date": "2026-06-25",
    "time": "16:00",
    "venue": "New York/New Jersey",
    "home": "ecuador",
    "away": "germany"
  },
  {
    "id": 57,
    "stage": "group",
    "group": "F",
    "date": "2026-06-25",
    "time": "18:00",
    "venue": "Dallas",
    "home": "japan",
    "away": "sweden"
  },
  {
    "id": 58,
    "stage": "group",
    "group": "F",
    "date": "2026-06-25",
    "time": "18:00",
    "venue": "Kansas City",
    "home": "tunisia",
    "away": "netherlands"
  },
  {
    "id": 59,
    "stage": "group",
    "group": "D",
    "date": "2026-06-25",
    "time": "19:00",
    "venue": "Los Angeles",
    "home": "turkiye",
    "away": "usa"
  },
  {
    "id": 60,
    "stage": "group",
    "group": "D",
    "date": "2026-06-25",
    "time": "19:00",
    "venue": "San Francisco Bay Area",
    "home": "paraguay",
    "away": "australia"
  },
  {
    "id": 61,
    "stage": "group",
    "group": "I",
    "date": "2026-06-26",
    "time": "15:00",
    "venue": "Boston",
    "home": "norway",
    "away": "france"
  },
  {
    "id": 62,
    "stage": "group",
    "group": "I",
    "date": "2026-06-26",
    "time": "15:00",
    "venue": "Toronto",
    "home": "senegal",
    "away": "iraq"
  },
  {
    "id": 63,
    "stage": "group",
    "group": "G",
    "date": "2026-06-26",
    "time": "20:00",
    "venue": "Seattle",
    "home": "egypt",
    "away": "iran"
  },
  {
    "id": 64,
    "stage": "group",
    "group": "G",
    "date": "2026-06-26",
    "time": "20:00",
    "venue": "Vancouver",
    "home": "new-zealand",
    "away": "belgium"
  },
  {
    "id": 65,
    "stage": "group",
    "group": "H",
    "date": "2026-06-26",
    "time": "19:00",
    "venue": "Houston",
    "home": "cape-verde",
    "away": "saudi-arabia"
  },
  {
    "id": 66,
    "stage": "group",
    "group": "H",
    "date": "2026-06-26",
    "time": "18:00",
    "venue": "Guadalajara",
    "home": "uruguay",
    "away": "spain"
  },
  {
    "id": 67,
    "stage": "group",
    "group": "L",
    "date": "2026-06-27",
    "time": "17:00",
    "venue": "New York/New Jersey",
    "home": "panama",
    "away": "england"
  },
  {
    "id": 68,
    "stage": "group",
    "group": "L",
    "date": "2026-06-27",
    "time": "17:00",
    "venue": "Philadelphia",
    "home": "croatia",
    "away": "ghana"
  },
  {
    "id": 69,
    "stage": "group",
    "group": "J",
    "date": "2026-06-27",
    "time": "21:00",
    "venue": "Kansas City",
    "home": "algeria",
    "away": "austria"
  },
  {
    "id": 70,
    "stage": "group",
    "group": "J",
    "date": "2026-06-27",
    "time": "21:00",
    "venue": "Dallas",
    "home": "jordan",
    "away": "argentina"
  },
  {
    "id": 71,
    "stage": "group",
    "group": "K",
    "date": "2026-06-27",
    "time": "19:30",
    "venue": "Miami",
    "home": "colombia",
    "away": "portugal"
  },
  {
    "id": 72,
    "stage": "group",
    "group": "K",
    "date": "2026-06-27",
    "time": "19:30",
    "venue": "Atlanta",
    "home": "congo-dr",
    "away": "uzbekistan"
  },
  {
    "id": 73,
    "stage": "r32",
    "group": "R32",
    "date": "2026-06-28",
    "time": "12:00",
    "venue": "Los Angeles",
    "home": "2º Grupo A vs 2º Grupo B",
    "away": "",
    "knockout": true
  },
  {
    "id": 74,
    "stage": "r32",
    "group": "R32",
    "date": "2026-06-29",
    "time": "16:30",
    "venue": "Boston",
    "home": "1º Grupo E vs 3º A/B/C/D/F",
    "away": "",
    "knockout": true
  },
  {
    "id": 75,
    "stage": "r32",
    "group": "R32",
    "date": "2026-06-29",
    "time": "19:00",
    "venue": "Monterrey",
    "home": "1º Grupo F vs 2º Grupo C",
    "away": "",
    "knockout": true
  },
  {
    "id": 76,
    "stage": "r32",
    "group": "R32",
    "date": "2026-06-29",
    "time": "12:00",
    "venue": "Houston",
    "home": "1º Grupo C vs 2º Grupo F",
    "away": "",
    "knockout": true
  },
  {
    "id": 77,
    "stage": "r32",
    "group": "R32",
    "date": "2026-06-30",
    "time": "17:00",
    "venue": "New York/New Jersey",
    "home": "1º Grupo I vs 3º C/D/F/G/H",
    "away": "",
    "knockout": true
  },
  {
    "id": 78,
    "stage": "r32",
    "group": "R32",
    "date": "2026-06-30",
    "time": "12:00",
    "venue": "Dallas",
    "home": "2º Grupo E vs 2º Grupo I",
    "away": "",
    "knockout": true
  },
  {
    "id": 79,
    "stage": "r32",
    "group": "R32",
    "date": "2026-06-30",
    "time": "19:00",
    "venue": "Mexico City",
    "home": "1º Grupo A vs 3º C/E/F/H/I",
    "away": "",
    "knockout": true
  },
  {
    "id": 80,
    "stage": "r32",
    "group": "R32",
    "date": "2026-07-01",
    "time": "12:00",
    "venue": "Atlanta",
    "home": "1º Grupo L vs 3º E/H/I/J/K",
    "away": "",
    "knockout": true
  },
  {
    "id": 81,
    "stage": "r32",
    "group": "R32",
    "date": "2026-07-01",
    "time": "17:00",
    "venue": "San Francisco Bay Area",
    "home": "1º Grupo D vs 3º B/E/F/I/J",
    "away": "",
    "knockout": true
  },
  {
    "id": 82,
    "stage": "r32",
    "group": "R32",
    "date": "2026-07-01",
    "time": "13:00",
    "venue": "Seattle",
    "home": "1º Grupo G vs 3º A/E/H/I/J",
    "away": "",
    "knockout": true
  },
  {
    "id": 83,
    "stage": "r32",
    "group": "R32",
    "date": "2026-07-02",
    "time": "19:00",
    "venue": "Toronto",
    "home": "2º Grupo K vs 2º Grupo L",
    "away": "",
    "knockout": true
  },
  {
    "id": 84,
    "stage": "r32",
    "group": "R32",
    "date": "2026-07-02",
    "time": "12:00",
    "venue": "Los Angeles",
    "home": "1º Grupo H vs 2º Grupo J",
    "away": "",
    "knockout": true
  },
  {
    "id": 85,
    "stage": "r32",
    "group": "R32",
    "date": "2026-07-02",
    "time": "20:00",
    "venue": "Vancouver",
    "home": "1º Grupo B vs 3º E/F/G/I/J",
    "away": "",
    "knockout": true
  },
  {
    "id": 86,
    "stage": "r32",
    "group": "R32",
    "date": "2026-07-03",
    "time": "18:00",
    "venue": "Miami",
    "home": "1º Grupo J vs 2º Grupo H",
    "away": "",
    "knockout": true
  },
  {
    "id": 87,
    "stage": "r32",
    "group": "R32",
    "date": "2026-07-03",
    "time": "20:30",
    "venue": "Kansas City",
    "home": "1º Grupo K vs 3º D/E/I/J/L",
    "away": "",
    "knockout": true
  },
  {
    "id": 88,
    "stage": "r32",
    "group": "R32",
    "date": "2026-07-03",
    "time": "13:00",
    "venue": "Dallas",
    "home": "2º Grupo D vs 2º Grupo G",
    "away": "",
    "knockout": true
  },
  {
    "id": 89,
    "stage": "r16",
    "group": "R16",
    "date": "2026-07-04",
    "time": "17:00",
    "venue": "Philadelphia",
    "home": "Ganador P74 vs Ganador P77",
    "away": "",
    "knockout": true
  },
  {
    "id": 90,
    "stage": "r16",
    "group": "R16",
    "date": "2026-07-04",
    "time": "12:00",
    "venue": "Houston",
    "home": "Ganador P73 vs Ganador P75",
    "away": "",
    "knockout": true
  },
  {
    "id": 91,
    "stage": "r16",
    "group": "R16",
    "date": "2026-07-05",
    "time": "16:00",
    "venue": "New York/New Jersey",
    "home": "Ganador P76 vs Ganador P78",
    "away": "",
    "knockout": true
  },
  {
    "id": 92,
    "stage": "r16",
    "group": "R16",
    "date": "2026-07-05",
    "time": "18:00",
    "venue": "Mexico City",
    "home": "Ganador P79 vs Ganador P80",
    "away": "",
    "knockout": true
  },
  {
    "id": 93,
    "stage": "r16",
    "group": "R16",
    "date": "2026-07-06",
    "time": "14:00",
    "venue": "Dallas",
    "home": "Ganador P83 vs Ganador P84",
    "away": "",
    "knockout": true
  },
  {
    "id": 94,
    "stage": "r16",
    "group": "R16",
    "date": "2026-07-06",
    "time": "17:00",
    "venue": "Seattle",
    "home": "Ganador P81 vs Ganador P82",
    "away": "",
    "knockout": true
  },
  {
    "id": 95,
    "stage": "r16",
    "group": "R16",
    "date": "2026-07-07",
    "time": "12:00",
    "venue": "Atlanta",
    "home": "Ganador P86 vs Ganador P88",
    "away": "",
    "knockout": true
  },
  {
    "id": 96,
    "stage": "r16",
    "group": "R16",
    "date": "2026-07-07",
    "time": "13:00",
    "venue": "Vancouver",
    "home": "Ganador P85 vs Ganador P87",
    "away": "",
    "knockout": true
  },
  {
    "id": 97,
    "stage": "qf",
    "group": "QF",
    "date": "2026-07-09",
    "time": "16:00",
    "venue": "Boston",
    "home": "Ganador P89 vs Ganador P90",
    "away": "",
    "knockout": true
  },
  {
    "id": 98,
    "stage": "qf",
    "group": "QF",
    "date": "2026-07-10",
    "time": "12:00",
    "venue": "Los Angeles",
    "home": "Ganador P93 vs Ganador P94",
    "away": "",
    "knockout": true
  },
  {
    "id": 99,
    "stage": "qf",
    "group": "QF",
    "date": "2026-07-11",
    "time": "17:00",
    "venue": "Miami",
    "home": "Ganador P91 vs Ganador P92",
    "away": "",
    "knockout": true
  },
  {
    "id": 100,
    "stage": "qf",
    "group": "QF",
    "date": "2026-07-11",
    "time": "20:00",
    "venue": "Kansas City",
    "home": "Ganador P95 vs Ganador P96",
    "away": "",
    "knockout": true
  },
  {
    "id": 101,
    "stage": "sf",
    "group": "SF",
    "date": "2026-07-14",
    "time": "14:00",
    "venue": "Dallas",
    "home": "Ganador P97 vs Ganador P98",
    "away": "",
    "knockout": true
  },
  {
    "id": 102,
    "stage": "sf",
    "group": "SF",
    "date": "2026-07-15",
    "time": "15:00",
    "venue": "Atlanta",
    "home": "Ganador P99 vs Ganador P100",
    "away": "",
    "knockout": true
  },
  {
    "id": 103,
    "stage": "third",
    "group": "THIRD",
    "date": "2026-07-18",
    "time": "17:00",
    "venue": "Miami",
    "home": "Perdedor SF1 vs Perdedor SF2",
    "away": "",
    "knockout": true
  },
  {
    "id": 104,
    "stage": "final",
    "group": "FINAL",
    "date": "2026-07-19",
    "time": "15:00",
    "venue": "New York/New Jersey",
    "home": "Ganador SF1 vs Ganador SF2",
    "away": "",
    "knockout": true
  }
];
