const TEAMS = {
  mexico: { name: 'México', flag: '🇲🇽', group: 'A' },
  'south-africa': { name: 'Sudáfrica', flag: '🇿🇦', group: 'A' },
  'korea-republic': { name: 'Corea del Sur', flag: '🇰🇷', group: 'A' },
  czechia: { name: 'Chequia', flag: '🇨🇿', group: 'A' },
  canada: { name: 'Canadá', flag: '🇨🇦', group: 'B' },
  switzerland: { name: 'Suiza', flag: '🇨🇭', group: 'B' },
  qatar: { name: 'Catar', flag: '🇶🇦', group: 'B' },
  'bosnia-herzegovina': { name: 'Bosnia y Herzegovina', flag: '🇧🇦', group: 'B' },
  brazil: { name: 'Brasil', flag: '🇧🇷', group: 'C' },
  morocco: { name: 'Marruecos', flag: '🇲🇦', group: 'C' },
  haiti: { name: 'Haití', flag: '🇭🇹', group: 'C' },
  scotland: { name: 'Escocia', flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', group: 'C' },
  usa: { name: 'EE.UU.', flag: '🇺🇸', group: 'D' },
  paraguay: { name: 'Paraguay', flag: '🇵🇾', group: 'D' },
  australia: { name: 'Australia', flag: '🇦🇺', group: 'D' },
  turkiye: { name: 'Turquía', flag: '🇹🇷', group: 'D' },
  germany: { name: 'Alemania', flag: '🇩🇪', group: 'E' },
  curacao: { name: 'Curazao', flag: '🇨🇼', group: 'E' },
  'ivory-coast': { name: 'Costa de Marfil', flag: '🇨🇮', group: 'E' },
  ecuador: { name: 'Ecuador', flag: '🇪🇨', group: 'E' },
  netherlands: { name: 'Países Bajos', flag: '🇳🇱', group: 'F' },
  japan: { name: 'Japón', flag: '🇯🇵', group: 'F' },
  tunisia: { name: 'Túnez', flag: '🇹🇳', group: 'F' },
  sweden: { name: 'Suecia', flag: '🇸🇪', group: 'F' },
  belgium: { name: 'Bélgica', flag: '🇧🇪', group: 'G' },
  egypt: { name: 'Egipto', flag: '🇪🇬', group: 'G' },
  iran: { name: 'Irán', flag: '🇮🇷', group: 'G' },
  'new-zealand': { name: 'Nueva Zelanda', flag: '🇳🇿', group: 'G' },
  spain: { name: 'España', flag: '🇪🇸', group: 'H' },
  'cape-verde': { name: 'Cabo Verde', flag: '🇨🇻', group: 'H' },
  'saudi-arabia': { name: 'Arabia Saudita', flag: '🇸🇦', group: 'H' },
  uruguay: { name: 'Uruguay', flag: '🇺🇾', group: 'H' },
  france: { name: 'Francia', flag: '🇫🇷', group: 'I' },
  senegal: { name: 'Senegal', flag: '🇸🇳', group: 'I' },
  norway: { name: 'Noruega', flag: '🇳🇴', group: 'I' },
  iraq: { name: 'Irak', flag: '🇮🇶', group: 'I' },
  argentina: { name: 'Argentina', flag: '🇦🇷', group: 'J' },
  algeria: { name: 'Argelia', flag: '🇩🇿', group: 'J' },
  austria: { name: 'Austria', flag: '🇦🇹', group: 'J' },
  jordan: { name: 'Jordania', flag: '🇯🇴', group: 'J' },
  portugal: { name: 'Portugal', flag: '🇵🇹', group: 'K' },
  uzbekistan: { name: 'Uzbekistán', flag: '🇺🇿', group: 'K' },
  colombia: { name: 'Colombia', flag: '🇨🇴', group: 'K' },
  'congo-dr': { name: 'RD Congo', flag: '🇨🇩', group: 'K' },
  england: { name: 'Inglaterra', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', group: 'L' },
  croatia: { name: 'Croacia', flag: '🇭🇷', group: 'L' },
  ghana: { name: 'Ghana', flag: '🇬🇭', group: 'L' },
  panama: { name: 'Panamá', flag: '🇵🇦', group: 'L' },
};

const VENUE_TZ = {
  'Mexico City': 'America/Mexico_City',
  Guadalajara: 'America/Mexico_City',
  Monterrey: 'America/Mexico_City',
  Toronto: 'America/Toronto',
  Vancouver: 'America/Vancouver',
  'Los Angeles': 'America/Los_Angeles',
  'San Francisco Bay Area': 'America/Los_Angeles',
  Seattle: 'America/Los_Angeles',
  Boston: 'America/New_York',
  'New York/New Jersey': 'America/New_York',
  Philadelphia: 'America/New_York',
  Miami: 'America/New_York',
  Atlanta: 'America/New_York',
  Dallas: 'America/Chicago',
  Houston: 'America/Chicago',
  'Kansas City': 'America/Chicago',
};
